import type { CatalogueBook } from "@/components/sections/CatalogueGrid";

/**
 * catalogue.ts — DATA for the /catalogue page (ported from catalogue.html).
 */
export const CATALOGUE_STATS = [
  { value: "08", label: "Collections" },
  { value: "500+", label: "Products" },
  { value: "2024", label: "Edition" },
];

export const CATALOGUE_BOOKS: CatalogueBook[] = [
  {
    title: "Master",
    titleLine2: "Collection 2024",
    eyebrow: "Complete Collection",
    spine: "R Ceramica · 2024",
    pages: "148 Pages",
    size: "PDF · 24 MB",
    subtitle: "Tiles · Bathrooms · Kitchen · Accessories",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800",
    categories: "all tiles bathroom kitchen slabs outdoor technical",
    badge: { label: "New Edition", accent: true },
  },
  {
    title: "Architectural",
    titleLine2: "Tiles",
    eyebrow: "Surface Studio",
    spine: "R Ceramica · Tiles",
    pages: "96 Pages",
    size: "PDF · 18 MB",
    subtitle: "Floor · Wall · Large Format · Mosaic",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&q=80&w=800",
    categories: "tiles",
  },
  {
    title: "Bathroom",
    titleLine2: "Collection",
    eyebrow: "Sanctuary Series",
    spine: "R Ceramica · Bath",
    pages: "112 Pages",
    size: "PDF · 21 MB",
    subtitle: "Faucets · Showers · Basins · Accessories",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&q=80&w=800",
    categories: "bathroom",
    badge: { label: "Updated" },
  },
  {
    title: "Kitchen",
    titleLine2: "Concepts",
    eyebrow: "Culinary Studio",
    spine: "R Ceramica · Kitchen",
    pages: "64 Pages",
    size: "PDF · 12 MB",
    subtitle: "Counter Tops · Backsplash · Sinks",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=800",
    categories: "kitchen",
  },
  {
    title: "Large Format",
    titleLine2: "Slabs",
    eyebrow: "Monolith Series",
    spine: "R Ceramica · Slabs",
    pages: "80 Pages",
    size: "PDF · 32 MB",
    subtitle: "1200×2400 · 1600×3200 · Bookmatch",
    image: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?auto=format&fit=crop&q=80&w=800",
    categories: "slabs tiles",
    badge: { label: "Exclusive", accent: true },
  },
  {
    title: "Outdoor",
    titleLine2: "Porcelain",
    eyebrow: "Terrace & Garden",
    spine: "R Ceramica · Outdoor",
    pages: "72 Pages",
    size: "PDF · 15 MB",
    subtitle: "R11 Anti-Slip · Pool Copings · Pavers",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800",
    categories: "outdoor tiles",
  },
  {
    title: "Technical",
    titleLine2: "Data Sheets",
    eyebrow: "Engineering Specs",
    spine: "R Ceramica · Technical",
    pages: "48 Pages",
    size: "PDF · 8 MB",
    subtitle: "ISO Ratings · Certifications · Dimensions",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
    categories: "technical",
  },
  {
    title: "Lookbook",
    titleLine2: "2024",
    eyebrow: "Visual Inspiration",
    spine: "R Ceramica · Look",
    pages: "56 Pages",
    size: "PDF · 28 MB",
    subtitle: "Lifestyle · Interiors · Project Showcase",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=800",
    categories: "all",
    badge: { label: "Limited" },
    status: { label: "Limited Run", color: "#facc15" },
  },
];
